Todo/Todo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todoapp/',include("TodoApp.urls")),
    path('',include("user.urls")),
]

Todo/TodoApp/urls.py
from django.urls import path
from . import views

app_name = 'TodoApp'

urlpatterns = [
    path('today',views.todo_today, name='todo_today'),
    path('home',views.todo_home, name='todo_home'),
    path('todolist/<str:pk>/',views.todo_list, name='todo_list'),
    path('add_todo/<str:pk>',views.add_todo,name = 'add_todo'),
    path('create_list',views.create_list,name = 'create_list'),
    path('update_todo/<str:pk>/<int:id>',views.update_todo,name = 'update_todo'),
    path('delete_todo/<str:pk><int:id>',views.delete_todo,name = 'delete_todo'),
    path('delete_list/<str:pk>',views.delete_list,name = 'delete_list'),
    path('change_status/<str:pk>/<int:id>/<str:status>',views.change_status,name = 'change_status'),
    # path('search', views.search, name='search'),
    path('priority_sort/<str:pk>',views.priority_sort,name = 'priority_sort'),
    path('deadline_sort/<str:pk>',views.deadline_sort,name = 'deadline_sort'),
]

Todo/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    # path('user_list/',views.user_list, name='user_list'),
    path('index/',views.index, name='index'),
    path('register/',views.register, name='register'),
    path('',views.user_login, name='user_login'),
    path('user_logout/',views.user_logout, name='user_logout'),
    path('info/',views.info, name='info'),
]

Todo/TodoApp/models.py
from datetime import datetime, timedelta
from email.policy import default
from importlib.metadata import requires
from tkinter import Widget
from turtle import title
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.timezone import now

class ListTodo(models.Model):
    list_name = models.CharField(max_length=255,unique=True,null=True)
    list_counter = models.IntegerField(default=1)

    class Meta:
        db_table = 'list_todo'
    
    def __str__(self):
        return self.list_name

# Create your models here.
class Todo(models.Model):
    today = datetime.today()
    # tomorrow = datetime.strftime(today, '%Y-%m-%d')
    user = models.ForeignKey(
        'user.Users', on_delete = models.CASCADE
    )
    title = models.CharField(max_length=50)
    detail =models.CharField(max_length=200,null=True)
    status = models.BooleanField(default=False)
    deadline = models.DateField('期限',blank=True,default=now)
    priority = models.IntegerField(null=True)
    list_name = models.ForeignKey(
        'ListTodo',on_delete=models.CASCADE
    )
    created_at =  models.DateTimeField(help_text='作成日時',auto_now_add=True)
    updated_at = models.DateTimeField(help_text='更新日時',auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'todo'
    

# class Grope(models.Model):
#     grope_name = models.CharField(max_length=255)


Todo/TodoApp/forms.py
from dataclasses import fields
from django import forms
from django.core import validators
from .models import Todo,ListTodo
from django.contrib.admin.widgets import AdminDateWidget
from datetime import datetime, timedelta
from django.utils.timezone import now

today =now
# tomorrow = datetime.strftime(today, '%Y-%m-%d')

class ListForm(forms.ModelForm):
    list_name = forms.CharField(label="list_name")
    class Meta:
        model =ListTodo
        exclude= ("list_counter",)
        # widgets ={'list_name':}

class AddForm(forms.ModelForm):
    title = forms.CharField(label='title')
    detail = forms.CharField(label='detail',widget=forms.Textarea(attrs={'rows':1,'cols':20}),required=False)
    deadline = forms.DateField(label='deadline', widget=AdminDateWidget(),initial=today)
    priority  = forms.ChoiceField(label='priority', choices=(
        (1,'1'),
        (2,'2'),
        (3,'3'),
        (4,'4'),
        (5,'5'),
        ),widget=forms.Select,initial=1)

    class Meta:
        model = Todo
        exclude = ['user','status','created_at','updated_at',]
        widgets ={
            'deadline':AdminDateWidget(),
        }
    
class UpdateForm(forms.ModelForm):
    title = forms.CharField(label='title')
    detail = forms.CharField(label='detail',widget=forms.Textarea(attrs={'rows':1,'cols':20}),required=False)
    deadline = forms.DateField(label='deadline', widget=AdminDateWidget(),required=False,initial=today)
    priority  = forms.ChoiceField(label='priority', choices=(
        (1,'1'),
        (2,'2'),
        (3,'3'),
        (4,'4'),
        (5,'5'),
        ),widget=forms.Select,required=False)
    
    class Meta:
        model = Todo
        exclude = ['user','status','created_at','updated_at']
        # fields="__all__"
        widgets ={
            'deadline':AdminDateWidget(),
        }

Todo/TodoApp/views.py
from secrets import choice
from turtle import update
from unicodedata import category
from django.shortcuts import render,redirect
from .models import Todo,ListTodo
from . import forms
from django.http import HttpResponse , HttpResponseRedirect,Http404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
import datetime

# Create your views here.
#HTMLに表示
def todo_home(request):
    lists = ListTodo.objects.all()
    return render(request,'todoapp/todo_home.html',context={
        'lists':lists,
    })


def todo_today(request):
    now = datetime.datetime.now()
    print(now)
    done = Todo.objects.filter(status=True,deadline=now)
    not_done = Todo.objects.filter(status=False,deadline=now)
    return render(request,'todoapp/todo_today.html',context= {
        "done_list":done,
        "not_done_list":not_done,
    })


def create_list(request):
    list_form = forms.ListForm()
    if request.method == 'POST':
        list_form = forms.ListForm(request.POST)
        list_todo = list(ListTodo.objects.filter(list_name=request.POST.get('list_name')))
        if list_form.is_valid() :
            list_form.save()
            return HttpResponseRedirect('/todoapp/home')
        else:
            for i in range(1,1000):
                list_name = str(request.POST.get('list_name')) + "("+str(i)+")"
                if ListTodo.objects.filter(list_name=list_name).exists() == False:
                    break
                print(list_name)
                i = i+1
            new_list_todo = ListTodo(list_name=list_name)
            new_list_todo.save()
            return HttpResponseRedirect('/todoapp/home')
    return render(request,'todoapp/create_list.html',context={
        'form':list_form,
    })


def todo_list(request,pk):
    pk = pk
    list_name = ListTodo.objects.get(pk=pk)
    done = Todo.objects.filter(status=True,list_name=pk)
    not_done = Todo.objects.filter(status=False,list_name=pk)
    return render(request,'todoapp/todo_list.html',context= {
        "done_list":done,
        "not_done_list":not_done,
        "pk" :pk,
        'list_name':list_name,
    })

# Todo_list()

#新しいタスクを追加
def add_todo(request,pk):
    today = ""
    if pk == "None":
        today = pk
        pk = "1"
    list_todo = ListTodo.objects.get(pk=pk)
    form=forms.AddForm(initial={'list_name':list_todo})
    if request.method == "POST":
        form = forms.AddForm(request.POST) 
        if form.is_valid():
            form.instance.user=request.user
            print("成功したのでデータを保存します")
            form.save()
            if today == "None":
                return HttpResponseRedirect('/todoapp/today')
            return HttpResponseRedirect('/todoapp/todolist/'+ pk)
        else:
            print("失敗したので、エラーを表示します")
            print(form.errors)
    return render(request,'todoapp/form_page.html',context={
        "form":form,
        "pk" : pk,
    })

#タスクの更新(編集)
def update_todo(request,pk,id):
    todo = Todo.objects.get(id=id)
    if todo.user.id != request.user.id:
        raise Http404
    update = forms.UpdateForm(
        initial= {
            'user':todo.user,
            'title':todo.title, 'detail':todo.detail,
            'deadline':todo.deadline, 'priority':todo.priority,
            'list_name':todo.list_name
            }
    )
    if request.method == 'POST':
        update = forms.UpdateForm(request.POST)
        if update.is_valid():
            todo.user=request.user
            todo.title=request.POST.get("title")
            todo.detail=request.POST.get("detail")
            todo.deadline=request.POST.get("deadline")
            todo.priority=request.POST.get("priority")
            todo.list_name.list_name=request.POST.get("list_name")
            todo.save()
            return HttpResponseRedirect('/todoapp/todolist/'+pk)
        else:
            print("失敗したので、エラーを表示します")
            print(update.errors)
    return render(request,'todoapp/update_todo.html',context={
        'update':update,
        'todo':todo,
        'pk':pk,
    })

#タスクの削除
def delete_todo(request,pk,id):
    todo = Todo.objects.filter(id=id).delete()

    HttpResponse('削除しました')
    return HttpResponseRedirect('/todoapp/todolist/'+pk)

def delete_list(request,pk):
    list = ListTodo.objects.filter(pk=pk).delete()
    HttpResponse('削除しました')
    return HttpResponseRedirect('/todoapp/home')



def change_status(request,pk,id,status):
    todo = Todo.objects.get(id=id)
    if status == 'True':
        todo.status =  False
    elif status == 'False':
        todo.status = True
    todo.save()
    if pk == 'None':
        return HttpResponseRedirect('/todoapp/today')

    return HttpResponseRedirect('/todoapp/todolist/'+pk)


def priority_sort(request,pk):
    todos = Todo.objects.filter(list_name=pk).order_by('priority')
    done= todos.filter(status=True)
    not_done= todos.filter(status=False)
    messages.success(request, '優先度順')
    return render(request,'todoapp/todo_list.html',context={
            # 'todo_list':todos,
            'done_list':done,
            'not_done_list':not_done,
            'pk':pk
        })

def deadline_sort(request,pk):
    todos = Todo.objects.filter(list_name=pk).order_by('deadline')
    done= todos.filter(status=True)
    not_done= todos.filter(status=False)
    messages.success(request, '期限順')
    return render(request,'todoapp/todo_list.html',context={
            # 'todo_list':todos,
            'done_list':done,
            'not_done_list':not_done,
            'pk':pk,
                    })

Todo/templates/todoapp/create_list.html
{% extends "todoapp/index.html" %}
{% load widget_tweaks%}
{% block title %}Todo追加画面{{ block.super }}{% endblock %}

{% block content %}
<header>
        <a type="submit" class="ms-2 btn btn-primary" href="{% url 'TodoApp:todo_home' %}">戻る</a>
</header>

    <form class="row g-3 ms-3" method='POST'>{% csrf_token %}
    <div class="col-md-6 ">
        <label for="{{ form.list_name.id_for_label }}" class="form-label">Listname</label>
        {{ form.list_name|add_class:'form-control' }}
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary">create!</button>
    </div>
    </form>
{% endblock %}

Todo/templates/todoapp/form_page.html
{% extends "todoapp/index.html" %}
{% load widget_tweaks%}
{% block title %}Todo追加画面{{ block.super }}{% endblock %}
{% load static %}

{% block content %}
    <header>
        <a type="submit" class="ms-2 btn btn-primary" href="{% url 'TodoApp:todo_list' pk=pk %}">戻る</a>
    </header>
    
    {% block extrahead %}
    <head>
    {% comment %} <link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}"/> {% endcomment %}
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}"/>
    <script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/calendar.css' %}"/>
    {{ form.media }}
    <script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/admin/RelatedObjectLookups.js' %}"></script>
    </head>
    {% endblock %}

    <form class="row g-3 ms-3" method='POST'>{% csrf_token %}
    <div class="col-md-6">
        <label for="{{ form.title.id_for_label }}" class="form-label">title</label>
        {{ form.title|add_class:'form-control' }}
        <label for="{{form.detail.id_for_label}}" class="form-label" >Detail</label>
        {{ form.detail|add_class:'form-control'}}
    </div>
    <div class="col-md-6">
        <label for="{{form.deadline.id_for_label}}" class="form-label" >Deadline</label>
        {{form.deadline|add_class:'form-control'}}
    </div>
    <div class="col-md-6">
        <label for="{{form.list_name.id_for_label}}" class="form-label">Listname</label>
        {{form.list_name|add_class:'form-control'}}
        <label for="{{form.priority.id_for_label}}" class="form-label">Priority</label>
        {{form.priority|add_class:'form-control'}}
    
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary">+ Add</button>
    </div>
    </form>
{% endblock %}

Todo/templates/todoapp/index.html
<!doctype html>
<html class="no-js" lang="">

<head>
  <meta charset="utf-8">
  <title> {% block title %} Todolist{% endblock %}</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta property="og:title" content="">
  <meta property="og:type" content="">
  <meta property="og:url" content="">
  <meta property="og:image" content="">
  <!-- Place favicon.ico in the root directory -->

  <link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css" rel="stylesheet">
<!-- CSS only -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <script
  src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI="  crossorigin="anonymous"></script>
  <meta name="theme-color" content="#fafafa">
</head>

<body class='text-bg-white '>
  <h1 class="d-block p-2 text-bg-primary text">Todolist
  <header>  
    <p>
      {% if user.is_authenticated %}
        <a type="submit" class="ms-2 btn btn-primary" href="{% url 'TodoApp:todo_home' %}"> Todoリスト</a>
        <a type="submit" class="ms-2 btn btn-primary" href="{% url 'TodoApp:todo_today' %}"> 今日のTodo</a>
      {% endif %}
        <a class="btn btn-primary collapsed" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
          メニュー
        </font></font></a>
    </p>
    <div class="collapse" id="collapseExample" style="">
    {% if user.is_authenticated %}
      <a type="submit" class="ms-1 btn btn-primary" href="{% url 'user:user_logout' %}"> ログアウト</a>
    {% else %}
      <a type="submit" class="ms-1 btn btn-primary" href="{% url 'user:user_login' %}"> ログイン</a>
      <a type="submit" class="ms-1 btn btn-primary" href="{% url 'user:register' %}"> 登録</a>
    {% endif %}

    </div>
    </header>
    </h1>
  {% comment %} <script src="App.js"></script> {% endcomment %}
  {% block content %}{% endblock %}
  {% block javascript %}{% endblock%}
</body>
</html>

Todo/templates/todoapp/todo_home.html
{% extends "todoapp/index.html" %}
{% load static %}
{% load widget_tweaks%}
{% block title %}Todoホーム{{ block.super }}{% endblock %}

{% block content %}
    <header>
        <a type="submit" class="ms-2 btn btn-primary" href="{% url 'TodoApp:create_list' %}">リスト作成</a>
    </header>

        <table class="table table-hover table-white ms-2">
        <thead>
            <tr>
                <th scope="col">タイトル</th>
                <th scope="col"><img src="{% static "img/trash.png" %}" height="20" width="40"></th>
            </tr>
        </thead>
        <tbody>
    {% for list in lists %}
            <tr class="table-light">
                <td>   
                <a href="{% url 'TodoApp:todo_list' pk=list.pk %}">
                {{ list.list_name}}
                </td> 
                <td>
                <a href="{% url 'TodoApp:delete_list' pk=list.pk %}">
                <img src="{% static "img/trash.png" %}" height="20" width="40"></a>
                </td>
            </tr>
    {% endfor %}

<tr>
{% endblock %}

Todo/templates/todoapp/todo_list.html
{% extends 'todoapp/index.html' %}
{% load static %}
<link rel="stylesheet" href="{% static "css/todo_list.css" %}">
{% load widget_tweaks%}
{% block title %}Todo一覧画面 {{block.super}}{% endblock%}

{% block content %}
    <header class ="p-1">
        <div class="d-flex justify-content-left">

        {% comment %} Todo 追加 {% endcomment %}
        <a type="submit" class="ms-2 btn btn-primary" href="{% url 'TodoApp:add_todo' pk=pk %}">+追加</a>
        

            <div class="ms-3 dropdown">
                <a class="btn btn-primary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    並べ替え
                </a>
                <ul class="dropdown-menu">
                    <li><a type="submit" class="dropdown-item ms-1 btn btn-primary" href="{% url 'TodoApp:priority_sort'  pk=pk%}">優先度</a></li>
                    <li><a type="submit" class="dropdown-item ms-1 btn btn-primary" href="{% url 'TodoApp:deadline_sort' pk=pk%}">期限</a></li>
                </ul>
            </div>
        <a type="submit" class="ms-2 btn btn-primary" href="{% url 'TodoApp:todo_home'  %}">戻る</a>

        </div>



    </header>
    <h1>{{list_name}}</h1>

    <div class='mt-5 ms-2'>
        {% if messages %}
            {% for message in messages %}
                <h3>{{message}}</h3>
            {% endfor%}
        {% endif %}

    <table class="table table-light table-hover   ms-2">
        <thead>
            <tr>
                <th scope="col"  style="width: 15%">進捗</th>
                <th scope="col">タイトル</th>
                <th scope="col">期限</th>
                <th scope="col">優先度</th>
                <th scope="col"><img src="{% static "img/trash.png" %}" height="20" width="40"></th>
                
            </tr>
        </thead>
        <tbody>
    {% for todo in not_done_list %}
            <tr class="table-light" id="not_done">
                <td>   
                {% if todo.status == False%}
                <a href="{% url 'TodoApp:change_status' pk=pk id=todo.id status=todo.status %}">未完了</a>
                {% else%}
                    <a href="{% url 'TodoApp:change_status' pk=pk id=todo.id status=todo.status %}">完了</a>
                {% endif %}
                </td> 
                <td>
                <a href=" {% url 'TodoApp:update_todo' pk=pk id=todo.id %}">{{todo.title}} </a>
                </td>
                <td>
                {{todo.deadline}}  
                </td>
                <td>
                {{todo.priority}} 
                </td>
                <td>
                <a href="{% url 'TodoApp:delete_todo' pk=pk id=todo.id %}">
                <img src="{% static "img/trash.png" %}" height="20" width="40"></a>
                </td>
            </tr>
            {% endfor %}

<tr>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>

        {% for todo in done_list %}
            <tr class="table-light " id = "done">
                <td>   
                {% if todo.status == False%}
                <a href="{% url 'TodoApp:change_status' pk=pk id=todo.id status=todo.status %}">未完了</a>
                {% else%}
                    <a href="{% url 'TodoApp:change_status' pk=pk id=todo.id status=todo.status %}">完了</a>
                {% endif %}
                </td> 
                <td>
                <a href=" {% url 'TodoApp:update_todo' pk=pk id=todo.id %}">{{todo.title}} </a>
                </td>
                <td>
                {{todo.deadline}}  
                </td>
                <td>
                {{todo.priority}} 
                </td>
                <td>
                <a href="{% url 'TodoApp:delete_todo' pk=pk id=todo.id %}">
                <img src="{% static "img/trash.png" %}" height="20" width="40"></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    </div>
    
{% endblock %}

Todo/templates/todoapp/todo_today.html
{% extends 'todoapp/index.html' %}
{% load static %}
<link rel="stylesheet" href="{% static "css/todo_list.css" %}">
{% block title %}Today's Todo {{block.super}}{% endblock%}

{% block content %}
<h1>Today's Todo!</h1>
    <header class ="p-1">
        <div class="d-flex justify-content-left">
            <a type="submit" class="ms-1 btn btn-primary" href="{% url 'TodoApp:add_todo' pk=None %}">+追加</a>    
            <div class="ms-3 dropdown">
                <a class="btn btn-primary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    並べ替え
                </a>
                <ul class="dropdown-menu">
                    <li><a type="submit" class="dropdown-item ms-1 btn btn-primary" href="{% url 'TodoApp:priority_sort' pk=None %}">優先度</a>    </li>
                    <li><a type="submit" class="dropdown-item ms-1 btn btn-primary" href="{% url 'TodoApp:deadline_sort' pk=None%}">期限</a></li>
                </ul>
            </div>
        </div>



    </header>
    <div class='mt-5'>
        {% if messages %}
            {% for message in messages %}
                <h3>{{message}}</h3>
            {% endfor%}
        {% endif %}

    <table class="table table-hover table-white ms-2">
        <thead>
            <tr>
                <th scope="col"  style="width: 15%">進捗</th>
                <th scope="col">タイトル</th>
                <th scope="col">期限</th>
                <th scope="col">優先度</th>
                <th scope="col">リスト名</th>
                <th scope="col"><img src="{% static "img/trash.png" %}" height="20" width="40"></th>
                
            </tr>
        </thead>
        <tbody>
    {% for todo in not_done_list %}
            <tr class="table-active" id="not_done">
                <td>   
                {% if todo.status == False%}
                <a href="{% url 'TodoApp:change_status' pk=None id=todo.id status=todo.status %}">未完了</a>
                {% else%}
                    <a href="{% url 'TodoApp:change_status' pk=None id=todo.id status=todo.status %}">完了</a>
                {% endif %}
                </td> 
                <td>
                <a href=" {% url 'TodoApp:update_todo' pk=None id=todo.id %}">{{todo.title}} </a>
                </td>
                <td>
                {{todo.deadline}}  
                </td>
                <td>
                {{todo.priority}} 
                </td>
                <td>
                {{todo.list_name}} 
                </td>
                <td>
                <a href="{% url 'TodoApp:delete_todo' pk=None id=todo.id %}">
                <img src="{% static "img/trash.png" %}" height="20" width="40"></a>
                </td>
            </tr>
            {% endfor %}

<tr>
<td></td>
</tr>

        {% for todo in done_list %}
            <tr class="table-active" id = "done">
                <td>   
                {% if todo.status == False%}
                <a href="{% url 'TodoApp:change_status' pk=None id=todo.id status=todo.status %}">未完了</a>
                {% else%}
                    <a href="{% url 'TodoApp:change_status' pk=None id=todo.id status=todo.status %}">完了</a>
                {% endif %}
                </td> 
                <td>
                <a href=" {% url 'TodoApp:update_todo' pk=None id=todo.id %}">{{todo.title}} </a>
                </td>
                <td>
                {{todo.deadline}}  
                </td>
                <td>
                {{todo.priority}} 
                </td>
                <td>
                {{todo.list_name}} 
                </td>
                <td>
                <a href="{% url 'TodoApp:delete_todo' pk=None id=todo.id %}">
                <img src="{% static "img/trash.png" %}" height="20" width="40"></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

        <div class="done" >
        </div>
    </div>
    
{% endblock %}

Todo/templates/todoapp/update_todo.html
{% extends "todoapp/index.html" %}
{% load widget_tweaks%}
{% load static %}
{% block title %}Todo編集画面{{ block.super }}{% endblock %}

{% block content %}
    <header>
        <a type="submit" class="ms-2 btn btn-primary" href="{% url 'TodoApp:todo_list' pk=pk %}">戻る</a>
    </header>

    {% block extrahead %}
    <head>
    {% comment %} <link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}"/> {% endcomment %}
    <link rel="stylesheet" type="text/css" href="{% static 'admin/css/forms.css' %}"/>
    <script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/calendar.css' %}"/>
    {{ update.media }}
    <script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>
    <script type="text/javascript" src="{% static 'admin/js/admin/RelatedObjectLookups.js' %}"></script>
    </head>
    {% endblock %}

    <form class="row g-3" method='POST'>{% csrf_token %}
    <div class="col-md-6">
        <label for="{{ update.title.id_for_label }}" class="form-label">title</label>
        {{ update.title|add_class:'form-control' }}
        <label for="{{update.detail.id_for_label}}" class="form-label" >Detail</label>
        {{ update.detail|add_class:'form-control'}}
    </div>
    <div class="col-5">
        <label for="{{update.deadline.id_for_label}}" class="form-label" >Deadline</label>
        {{update.deadline|add_class:'form-control'}}
    </div>
    <div class="col-md-5">
        <label for="{{update.priority.id_for_label}}" class="form-label">Priority</label>
        {{update.priority|add_class:'form-control'}}
        
    </div>
    <div class="col-md-4">
        <label for="{{update.list_name.id_for_label}}" class="form-label">Listname</label>
        {{update.list_name|add_class:'form-control'}}
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary">+ Update</button>
    </div>
    </form>
{% endblock %}