Todo/Todo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todoapp/',include("TodoApp.urls")),
    path('',include("user.urls")),
]

Todo/TodoApp/urls.py
from django.urls import path
from . import views

app_name = 'TodoApp'

urlpatterns = [
    path('today',views.todo_today, name='todo_today'),
    path('home',views.todo_home, name='todo_home'),
    path('todolist/<str:pk>/',views.todo_list, name='todo_list'),
    path('add_todo/<str:pk>',views.add_todo,name = 'add_todo'),
    path('create_list',views.create_list,name = 'create_list'),
    path('update_todo/<str:pk>/<int:id>',views.update_todo,name = 'update_todo'),
    path('delete_todo/<str:pk><int:id>',views.delete_todo,name = 'delete_todo'),
    path('delete_list/<str:pk>',views.delete_list,name = 'delete_list'),
    path('change_status/<str:pk>/<int:id>/<str:status>',views.change_status,name = 'change_status'),
    # path('search', views.search, name='search'),
    path('priority_sort/<str:pk>',views.priority_sort,name = 'priority_sort'),
    path('deadline_sort/<str:pk>',views.deadline_sort,name = 'deadline_sort'),
]

Todo/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    # path('user_list/',views.user_list, name='user_list'),
    path('index/',views.index, name='index'),
    path('register/',views.register, name='register'),
    path('',views.user_login, name='user_login'),
    path('user_logout/',views.user_logout, name='user_logout'),
    path('info/',views.info, name='info'),
]

Todo/user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import (AbstractBaseUser ,BaseUserManager, PermissionsMixin)
from django.contrib.auth.models import UserManager

# Create your models here.


class Users(AbstractBaseUser,PermissionsMixin):
    username= models.CharField(max_length = 255)
    email = models.EmailField(max_length= 255,unique=True)
    is_staff = models.BooleanField(default=True)
    
    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        db_table = 'users'



    

Todo/user/forms.py
from dataclasses import fields
from django import forms
from django.contrib.auth.models import User
from .models import Users
from django.contrib.auth.password_validation import validate_password


class RegistForm(forms.ModelForm):
    username= forms.CharField(label='username')
    email=forms.EmailField(label='email')
    password = forms.CharField(label='password',widget=forms.PasswordInput())
    confirm_password = forms.CharField(label='confirm_password',widget=forms.PasswordInput())

    class Meta:
        model = Users
        fields = ('username','email','password')
    
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data['password']
        confirm_password = cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('パスワードが一致しません')
    
    def save(self,commit=False):
        user = super().save(commit=False)
        validate_password(self.cleaned_data['password'],user)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user

class LoginForm(forms.Form):
    email = forms.CharField(label='名前')
    password = forms.CharField(label='パスワード',widget=forms.PasswordInput())

Todo/user/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from . import forms
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.core.exceptions import ValidationError
from django.contrib import messages



def index(request):
    return render(request,'user/index.html')

def register(request):
    user_form = forms.RegistForm(request.POST or None)
    if user_form.is_valid(): # validation
        try:
            user_form.save()
            return redirect('user:user_login')
        except ValidationError as e:
            user_form.add_error('password',e)
    return render(request ,'user/registration.html', context={
        'user_form':user_form,
    })

def user_login(request):
    login_form  = forms.LoginForm(request.POST or None)
    if login_form.is_valid():
        email = login_form.cleaned_data.get('email')
        password = login_form.cleaned_data.get('password')
        user = authenticate(email =email, password=password) #userが存在するかつ情報があっているか確認
        # print(password)
        if user: #user exist
            login(request,user)
            return redirect('TodoApp:todo_home')
        else:
            messages.warning(request,'ユーザかパスワードが間違っています')
    return render(request,'user/login.html',context={
        'login_form':login_form
    })

#logout
@login_required
def user_logout(request):
    logout(request)
    return redirect('user:user_login')

@login_required
def info(request):
    return HttpResponse('ログインしています')

Todo/templates/user/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title></title>
    </head>
    <body>
    <nav>
        <a href="{% url 'user:index' %}">ホーム</a>
    {% if user.is_authenticated %}
        <a href="{% url 'user:user_logout' %}">ログアウト</a>
    {% else %}
        <a href="{% url 'user:register' %}">登録画面</a>
        <a href="{% url 'user:user_login' %}">ログイン</a>
    {% endif %}
        <a href="{% url 'user:info'%}">インフォメーション</a>
    </nav>
    <div>
        {% block content %}
        {% endblock %}
    </div>
    </body>
</html>

Todo/templates/user/index.html
<!doctype html>
<html class="no-js" lang="">

<head>
  <meta charset="utf-8">
  <title> {% block title %} Todolist{% endblock %}</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta property="og:title" content="">
  <meta property="og:type" content="">
  <meta property="og:url" content="">
  <meta property="og:image" content="">
  <!-- Place favicon.ico in the root directory -->

  <link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css" rel="stylesheet">
<!-- CSS only -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

  <meta name="theme-color" content="#fafafa">
</head>

<body class='text-bg-white '>
  <h1 class="d-block p-2 text-bg-primary text">Todolist
  <header>  
    <p>
        <a class="btn btn-primary collapsed" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">
        メニュー
        </font></font></a>
    </p>

    <div class="collapse" id="collapseExample" style="">
    <a type="submit" class="ms-1 btn btn-primary" href="{% url 'user:user_login' %}"> ログイン</a>
    <a type="submit" class="ms-1 btn btn-primary" href="{% url 'user:register' %}"> 登録</a>
    {% if user.is_authenticated %}
        <a type="submit" class="ms-2 btn btn-primary" href="{% url 'TodoApp:todo_list' %}"> Todoリスト</a>
        <a type="submit" class="ms-1 btn btn-primary" href="{% url 'user:user_logout' %}"> ログアウト</a>
    {% endif %}

    </div>
    </header>
    </h1>
  {% comment %} <script src="App.js"></script> {% endcomment %}
  {% block content %}{% endblock %}
</body>

</html>

Todo/templates/user/login.html
{% extends "todoapp/index.html" %}
{% load widget_tweaks%}
{% block title %}ログイン画面{{ block.super }}{% endblock %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
        <div>{{message}}</div>
        {% endfor %}
    {% endif%}
    <form class="row mb-3" method='POST'>{% csrf_token %}
    <div class="ms-3 mb-3">
        <label for="{{ login_form.email.id_for_label }}" class=" form-label">email</label>
        {{ login_form.email|add_class:'form-control' }}
        <ul>
            {% for error in login_form.password.errors %}
                <li>{{error}}</li>
            {% endfor %}
        </ul>
        <label for="{{login_form.password.id_for_label}}" class="form-label" >password</label>
        {{ login_form.password|add_class:'form-control'}}
    </div>
    <div class="ms-3 col-12">
        <button type="submit" class="btn btn-primary">Login</button>
    </div>
    </form>
    <div class="mt-4">
        <p>アカウントの登録はこちらから➡<a type="submit" class="ms-1 btn btn-primary" href="{% url 'user:register' %}"> 登録</a></p></div>
{% endblock %}

Todo/templates/user/registration.html
{% extends "todoapp/index.html" %}
{% load widget_tweaks%}
{% block title %}登録画面{{ block.super }}{% endblock %}

{% block content %}
    <form class="row g-3" method='POST'>{% csrf_token %}
    <div class="ms-3 col-md-6">
        <label for="{{ user_form.username.id_for_label }}" class="form-label">username</label>
        {{ user_form.username|add_class:'form-control' }}
            <ul>
                {% for error in user_form.email.errors %}
                    <li>{{error}}</li>
                {% endfor %}
            </ul>
        <label for="{{ user_form.email.id_for_label }}" class="form-label">email</label>
        {{ user_form.email|add_class:'form-control' }}
            <ul>
                {% for error in user_form.password.errors %}
                    <li>{{error}}</li>
                {% endfor %}
            </ul>
        <label for="{{user_form.password.id_for_label}}" class="form-label" >password</label>
        {{ user_form.password|add_class:'form-control'}}
            <ul>
                {% for error in user_form.non_field_errors %}
                    <li>{{error}}</li>
                {% endfor %}
            </ul>
        <label for="{{user_form.confirm_password.id_for_label}}" class="form-label" >confirm_password</label>
        {{ user_form.confirm_password|add_class:'form-control'}}
    </div>

    <div class="ms-3 col-12">
        <button type="submit" class="btn btn-primary">+ register</button>
    </div>
    </form>
{% endblock %}